#ifndef __QR_H
#define __QR_H

#include <stdint.h>
#include "qr_types.h"
#include "qr_debug.h"

class CQrGen {
    public:
        /**
         * Creates a QR code from raw data, renders the bitmap, adds format information and applies a mask
         * @param data raw data to encode
         * @param length length of the data
         * @param mode QR mode to use (default: QrMode::Unspecified, which means auto-detect)
         * @param ecLevel QR error correction level to use (default: QrEcc::L)
         * @return a QrCode object containing the encoded data and the rendered bitmap
         */
        QrCode* create(const char* data, uint16_t length, QrMode mode = QrMode::Unspecified, QrEcc ecLevel = QrEcc::L, uint8_t version = 40);

        /**
         * Creates a QR code from raw data without rendering the bitmap (allocates space though)
         * @param data raw data to encode
         * @param length length of the data
         * @param mode QR mode to use (default: QrMode::Unspecified, which means auto-detect)
         * @param ecLevel QR error correction level to use (default: QrEcc::L)
         * @return QrCode object
         */
        QrCode* createRaw(const char* data, uint16_t length, QrMode mode = QrMode::Unspecified, QrEcc ecLevel = QrEcc::L, uint8_t version = 40);
       
        /**
         * Sets the format information for a given QR code by mapping the error correction level 
         * and mask pattern to a 15-bit format string. The mapping involves a bitwise operation 
         * with a predefined mask, and the result is stored in the formatPoly field of the QR code. 
         * This function ensures that the error correction level (ecLevel) is mapped using a specific 
         * conversion table and the final format string is generated by performing a long division 
         * using a generator polynomial.
         *
         * @param code Pointer to the QrCode object whose format information is to be set.
         */        
        void setFormatPoly(QrCode *code);

        /**
         * Sets the version information for a given QR code by mapping the version number to a 18-bit 
         * version string. The mapping involves a bitwise operation with a predefined generator 
         * polynomial, and the result is stored in the versionPoly field of the QR code. This function 
         * ensures that the version number (version) is mapped using a specific conversion table and the 
         * final version string is generated by performing a long division using a generator polynomial.
         *
         * @param code Pointer to the QrCode object whose version information is to be set.
         */        
        void setVersionPoly(QrCode *code);

        /**
         * This function implements the Reed-Solomon error correction algorithm's long division step.
         * It takes a dividend (f) and a divisor (d), and performs the division in a way that the
         * remainder is computed using a bitwise XOR operation. The result is the remainder of the
         * division, which is then combined with the original dividend using a bitwise OR operation.
         * The result is returned as a uint32_t.
         * @param f Dividend (input)
         * @param d Divisor (input)
         * @param totalLength Total length of the dividend (input)
         * @param divisorLength Length of the divisor (input)
         * @return Result of the division (uint32_t)
         */
        uint32_t setEccBits(uint32_t f, uint32_t d, uint8_t totalLength, uint8_t divisorLength);
        
        /**
         * Applies the best mask to the QR code. It does this by computing the rank of the QR code with each mask and then
         * selecting the mask with the lowest rank.
         * @param code The QR code to apply the best mask to
         */
        void applyBestMask(QrCode *code);

        /**
         * Changes the mask applied to the given QR code by first removing the existing mask and then
         * applying the new specified mask. Updates the QR code's mask property and format information,
         * and re-renders the format to reflect the changes.
         *
         * @param code Pointer to the QrCode object to which the mask change should be applied.
         * @param mask The new mask pattern to apply to the QR code.
         */
        void changeMask(QrCode *code, uint8_t mask);
};

extern CQrGen QrGenerator;

#endif //__QR_H